'use client';
import {useState} from 'react';
import {PaintingHero} from '@/components/painting-hero';
import {SiteHeader} from '@/components/site-header';
import {SiteFooter} from '@/components/site-footer';
import {ArrowUpRight,Sun,Paintbrush,House,Building2,ClipboardCheck,HeartHandshake,MapPin,ArrowRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';

const photos = {
 hero:'/images/exterior.jpg',
 interior:'/images/interior.jpg',
 commercial:'/images/commercial.jpg',
 detail:'/images/detail.jpg',
};
const questions = [
 ['How do I get a painting estimate?', 'Tell us a little about your property, location, and the work you have in mind. A walkthrough helps establish surface conditions, preparation needs, colors, and an accurate written scope. Complete the estimate form to prepare an email, or call (949) 735-4026 to discuss your project.'],
 ['Do you paint both homes and commercial spaces?', 'Yes. Golden Coast Paintings offers interior and exterior painting for residential and commercial properties. Share your property type and any access or scheduling considerations with your estimate request.'],
 ['What preparation does a painting project involve?', 'Preparation depends on the surface. A project may include protecting furniture and landscaping, cleaning, filling small imperfections, sanding, caulking, and priming where needed. Your written estimate should spell out the preparation included.'],
 ['Can you help me choose colors and finishes?', 'Include any inspiration, existing finishes, and preferred colors when you contact us. Discuss sample colors in your own lighting and the right finish for each surface before work begins.'],
 ['How long will my project take?', 'Timing depends on project size, surface condition, product drying times, access, and weather for exterior work. Your schedule should be confirmed after a walkthrough, with any changes communicated along the way.'],
 ['Which areas do you serve?', 'The sample service area below focuses on Orange County and nearby coastal communities. Final service boundaries are awaiting business confirmation; include your city when requesting an estimate.'],
];
const projects = [
 {name:'A brighter welcome',type:'Exterior',image:photos.hero,detail:'Warm white stucco · contrasting trim'},
 {name:'Room to unwind',type:'Interior',image:photos.interior,detail:'Soft neutrals · light-filled living'},
 {name:'A fresh first impression',type:'Commercial',image:photos.commercial,detail:'Clean walls · considered workspaces'},
];
function CTA({children='Get a Free Estimate'}:{children?:React.ReactNode}){return <a className="button" href="/contact">{children}<ArrowUpRight size={18} aria-hidden="true"/></a>}
export default function Home(){
 const [filter,setFilter]=useState('All');
 return <><a className="skip-link" href="#main">Skip to content</a><SiteHeader home/>
 <main id="main"><PaintingHero/>
 <div className="trust-strip">{[[ClipboardCheck,'Clear, considered estimates'],[Paintbrush,'Care in every detail'],[House,'Respect for your space'],[HeartHandshake,'Communication that counts']].map(([Icon,label])=>{const I=Icon as typeof House;return <div key={String(label)}><I size={21}/><span>{String(label)}</span></div>})}</div>
 <section className="section services" id="services"><div className="section-heading"><div><p className="eyebrow">YOUR SPACE. OUR CANVAS.</p><h2>A fresh start,<br/>inside and out.</h2></div><p>From one favorite room to an entire property, a thoughtful paint job brings everything together. Let’s create a finish that feels right for you.</p></div><div className="service-grid"><article className="service-card"><img src={photos.interior} alt="Airy neutral living room with freshly painted walls" width="900" height="650" loading="lazy"/><div className="service-content"><div className="card-top"><span>01 / FOR YOUR HOME</span><House size={21}/></div><h3>Residential painting</h3><p>A home that feels more like you. Refresh your everyday spaces with colors you love and details that make a difference.</p><ul><li>Living rooms, bedrooms & kitchens</li><li>Whole-home interior & exterior painting</li><li>Walls, ceilings, doors & trim</li></ul><a href="/services#residential" className="service-link">Explore residential painting <ArrowUpRight size={18}/></a></div></article><article className="service-card"><img src={photos.commercial} alt="Modern commercial office with bright painted surfaces" width="900" height="650" loading="lazy"/><div className="service-content"><div className="card-top"><span>02 / FOR YOUR BUSINESS</span><Building2 size={21}/></div><h3>Commercial painting</h3><p>A space that works as hard as you do. Create a welcoming first impression for your customers, team, and community.</p><ul><li>Offices, retail & professional spaces</li><li>Interior & exterior property refreshes</li><li>Planning around access & operations</li></ul><a href="/services#commercial" className="service-link">Explore commercial painting <ArrowUpRight size={18}/></a></div></article></div><div className="specialties"><article><span className="icon-box"><Paintbrush/></span><div><h3>Interior painting</h3><p>Set the mood with smooth walls, crisp trim, and colors that bring every room to life.</p><a href="/services#interior">Refresh your interior <ArrowRight size={15}/></a></div></article><article><span className="icon-box blue"><Sun/></span><div><h3>Exterior painting</h3><p>Give your property a fresh welcome with thoughtful surface preparation and a cohesive finish.</p><a href="/services#exterior">Transform your exterior <ArrowRight size={15}/></a></div></article></div></section>
 <section className="why-section" id="about"><div className="why-photo"><img src={photos.detail} alt="Light-filled room with clean white walls and natural wood accents" width="1000" height="1100" loading="lazy"/><span className="photo-tag">IT’S THE DETAILS THAT MAKE THE DIFFERENCE.</span></div><div className="why-copy"><p className="eyebrow">THE GOLDEN COAST APPROACH</p><h2>More than a fresh coat.<br/><em>A little more care.</em></h2><p className="section-intro">The best part of a painting project should be enjoying the result. Our approach puts equal thought into the experience along the way.</p><div className="value-list">{[['01','Preparation with purpose','Great finishes start before the first coat. Protecting, preparing, and choosing the right approach sets the foundation.'],['02','Your space, respected','A considered work area and thoughtful cleanup help make the process feel easier from start to finish.'],['03','Clarity at every step','A written scope, an agreed schedule, and straightforward communication help keep everyone on the same page.']].map(([n,title,copy])=><div key={n}><span>{n}</span><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div><CTA>Let’s bring your vision to life</CTA></div></section>
 <section className="section gallery" id="projects"><div className="section-heading"><div><p className="eyebrow">A LITTLE INSPIRATION</p><h2>Picture the possibilities.</h2></div><p>Fresh palettes. Inviting spaces. Explore the kind of transformation a new coat of paint can inspire.</p></div><div className="gallery-toolbar"><div className="filters" aria-label="Filter inspiration gallery">{['All','Interior','Exterior','Commercial'].map(item=><Button key={item} variant="ghost" className={filter===item?'filter active':'filter'} aria-pressed={filter===item} onClick={()=>setFilter(item)}>{item}</Button>)}</div><small>Inspiration photography · not completed company projects</small></div><div className="project-grid">{projects.filter(p=>filter==='All'||filter===p.type).map(p=><article key={p.name}><div className="project-image"><img src={p.image} alt={p.detail} width="800" height="850" loading="lazy"/><span>{p.type}</span></div><h3>{p.name}</h3><p>{p.detail}</p></article>)}</div></section>
 <section className="process-section"><div className="section-heading"><div><p className="eyebrow">FROM FIRST HELLO TO FINAL WALKTHROUGH</p><h2>A clear path to a beautiful finish.</h2></div></div><div className="process-grid">{[['01','Tell us your vision','Share your space, your goals, and the timing you have in mind.'],['02','Make a thoughtful plan','Review the surfaces, scope, colors, and written estimate together.'],['03','Prepare. Paint. Refine.','Protect the space, prepare the surfaces, and bring the finish to life.'],['04','Enjoy the transformation','Walk through the finished work and make sure the details feel right.']].map(([n,title,copy])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
 <section className="section testimonials"><div className="section-heading"><div><p className="eyebrow">GOOD WORK. GOOD WORDS.</p><h2>The kind of experience<br/>we’re here to create.</h2></div><p className="sample-note">Sample testimonials for layout preview. Replace these with approved customer reviews before launch.</p></div><div className="testimonial-grid">{[['“The rooms feel lighter, brighter, and completely ours. The little details made all the difference.”','Residential customer'],['“From the first conversation to the final walkthrough, everything felt clear and well considered.”','Exterior painting customer'],['“A fresh, welcoming space for our team and clients. Exactly the feeling we wanted to create.”','Commercial customer']].map(([quote,label])=><figure key={label}><span className="quote-mark">“</span><blockquote>{quote}</blockquote><figcaption>{label}<small>Illustrative review · placeholder</small></figcaption></figure>)}</div></section>
 <section className="area-section"><div><p className="eyebrow">COASTAL ROOTS. LOCAL POSSIBILITIES.</p><h2>A golden touch<br/>for Southern California.</h2><p>From coastal cottages to neighborhood businesses, every property deserves to feel its best.</p><small>Proposed service area · confirm coverage with the business.</small></div><div><MapPin className="area-icon" size={32}/><h3>Orange County & nearby communities</h3><div className="cities">{['Newport Beach','Costa Mesa','Huntington Beach','Irvine','Laguna Beach','Dana Point'].map(city=><span key={city}>{city}</span>)}</div><a className="text-link" href="/contact">Tell us where your project is <ArrowUpRight size={16}/></a></div></section>
 <section className="section faq-section" id="faq"><div><p className="eyebrow">A FEW THINGS YOU MIGHT BE WONDERING</p><h2>Good questions.<br/>Clear answers.</h2><p>Have something else in mind?<br/><a href="/contact">Let’s talk about your project ↗</a></p></div><Accordion className="faq-list">{questions.map(([question,answer],i)=><AccordionItem key={question} value={String(i)}><AccordionTrigger>{question}</AccordionTrigger><AccordionContent>{answer}</AccordionContent></AccordionItem>)}</Accordion></section>
 <section className="home-contact-banner" id="quote"><div><p className="eyebrow">LET'S TALK ABOUT YOUR PROJECT</p><h2>Ready for a fresh start?</h2><p>Tell us about your home or business. Your next chapter starts with a conversation.</p></div><CTA>Contact Us for a Free Estimate</CTA></section>
 </main><SiteFooter/><a className="mobile-cta" href="/contact">Get a Free Estimate <ArrowUpRight size={18}/></a></>;
}

